language: ruby
rvm:
- 2.1.3
branches:
  only:
  - master
env:
- TEST_SUITE=rspec
- TEST_SUITE=cucumber
script:
- bundle exec rake app:transam_core:prepare_rspec
- bundle exec $TEST_SUITE
before_install:
- openssl aes-256-cbc -K $encrypted_1ed3e5c11482_key -iv $encrypted_1ed3e5c11482_iv
  -in spec/dummy/db/schema.rb.enc -out spec/dummy/db/schema.rb -d
