language: ruby
rvm:
- 2.2.1
branches:
  only:
  - master
env:
- TEST_SUITE=rspec
- TEST_SUITE=cucumber
before_install:
- export TZ="America/New_York" # set timezone
- mysql -e "create database IF NOT EXISTS transam_core_testing;" -uroot
- openssl aes-256-cbc -K $encrypted_8b7ffff52cb7_key -iv $encrypted_8b7ffff52cb7_iv -in spec/dummy/db/schema.rb.enc -out spec/dummy/db/schema.rb -d
addons:
  code_climate:
    repo_token: d5c0c26a73feef46179efdd2e5d8c26c464c2f2be870db3ebbd3bb620996d19c
before_script:
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_core:prepare_rspec
- bundle exec $TEST_SUITE
